"""Audio post-processing: normalize, fade, trim, metadata."""
import json
import numpy as np
import soundfile as sf
from pathlib import Path
from typing import Optional


def postprocess_audio(
    wav_path: Path,
    normalize: bool = True,
    fade: bool = True,
    trim: bool = False,
    metadata: bool = True,
    title: str = "",
    style: str = "",
    seed: int = 0,
    out_format: str = "pcm16",
    extra_meta: Optional[dict] = None,
) -> Path:
    """Apply selected post-processing steps to a WAV file. Returns the WAV path."""
    data, sr = sf.read(str(wav_path))
    original_format = _detect_format(wav_path)
    modified = False

    if trim:
        data, sr = _trim_silence(data, sr)
        modified = True

    if normalize:
        data = _normalize(data, target_db=-1.0)
        modified = True

    if fade:
        data = _fade(data, sr, fade_in_ms=500, fade_out_ms=500)
        modified = True

    if modified:
        subtype = _format_to_subtype(original_format)
        sf.write(str(wav_path), data, sr, subtype=subtype)

    if metadata:
        _embed_metadata(wav_path, title=title, style=style, seed=seed, extra=extra_meta)

    return wav_path


def _detect_format(wav_path: Path) -> str:
    """Detect the sample format of a WAV file."""
    info = sf.info(str(wav_path))
    mapping = {"PCM_16": "pcm16", "PCM_24": "pcm24", "FLOAT": "float32"}
    return mapping.get(info.subtype, "pcm16")


def _format_to_subtype(fmt: str) -> str:
    mapping = {"pcm16": "PCM_16", "pcm24": "PCM_24", "float32": "FLOAT"}
    return mapping.get(fmt, "PCM_16")


def _normalize(data: np.ndarray, target_db: float = -1.0) -> np.ndarray:
    """Normalize audio peak to target dB level."""
    peak = np.max(np.abs(data))
    if peak < 1e-8:
        return data
    target_linear = 10.0 ** (target_db / 20.0)
    gain = target_linear / peak
    return np.clip(data * gain, -1.0, 1.0)


def _fade(data: np.ndarray, sr: int, fade_in_ms: int = 500, fade_out_ms: int = 500) -> np.ndarray:
    """Apply fade-in and fade-out."""
    n = len(data)
    fade_in = min(int(sr * fade_in_ms / 1000), n)
    fade_out = min(int(sr * fade_out_ms / 1000), n)

    if fade_in > 0:
        ramp = np.linspace(0.0, 1.0, fade_in, dtype=data.dtype)
        if data.ndim > 1:
            ramp = ramp.reshape(-1, 1)
        data[:fade_in] *= ramp

    if fade_out > 0:
        ramp = np.linspace(1.0, 0.0, fade_out, dtype=data.dtype)
        if data.ndim > 1:
            ramp = ramp.reshape(-1, 1)
        data[-fade_out:] *= ramp

    return data


def _trim_silence(data: np.ndarray, sr: int, threshold_db: float = -40.0) -> tuple:
    """Trim silence from start and end."""
    threshold = 10.0 ** (threshold_db / 20.0)
    if data.ndim > 1:
        mono = np.max(np.abs(data), axis=1)
    else:
        mono = np.abs(data)

    above = np.where(mono > threshold)[0]
    if len(above) == 0:
        return data, sr

    start = max(0, above[0] - int(sr * 0.01))
    end = min(len(data), above[-1] + int(sr * 0.01) + 1)
    return data[start:end], sr


def _embed_metadata(wav_path: Path, title: str = "", style: str = "", seed: int = 0, extra: Optional[dict] = None):
    """Embed metadata: ID3 tags for WAV/FLAC + JSON sidecar.

    extra 为一组生成/采样参数（cfg、ODE 步数、批量、采样等），合并写入 sidecar JSON。
    """
    display_title = title or wav_path.parent.name
    comment = f"Style: {style} | Seed: {seed} | Generated by YuE2 Music Studio"

    sidecar = {"title": display_title, "style": style, "seed": seed, "generator": "YuE2 Music Studio"}
    if extra and isinstance(extra, dict):
        # 平铺合并，避免覆盖上面 4 个固定字段
        for k, v in extra.items():
            sidecar.setdefault(k, v)
    json_path = wav_path.with_suffix(".json")
    json_path.write_text(json.dumps(sidecar, ensure_ascii=False, indent=2), encoding="utf-8")

    try:
        from mutagen.id3 import ID3, TIT2, TPE1, COMM, ID3NoHeaderError

        if wav_path.suffix.lower() == ".flac":
            from mutagen.flac import FLAC
            audio = FLAC(str(wav_path))
            if not audio.tags:
                audio.add_tags()
            audio["title"] = display_title
            audio["artist"] = "YuE2 Music Studio"
            audio["comment"] = comment
            audio.save()
        else:
            audio = ID3(str(wav_path))
            audio.add(TIT2(encoding=3, text=[display_title]))
            audio.add(TPE1(encoding=3, text=["YuE2 Music Studio"]))
            audio.add(COMM(encoding=3, lang="zho", desc="Comment", text=[comment]))
            audio.save(str(wav_path))
    except Exception:
        pass
